const quizData = {
    // Club-specific pools (10 each - as provided in previous turns)
    "Arsenal": [ /* Insert the 10 Arsenal Qs here */ ],
    "Real Madrid": [ /* Insert the 10 Madrid Qs here */ ],
    "Chelsea": [ /* Insert the 10 Chelsea Qs here */ ],
    "Manchester United": [ /* Insert the 10 United Qs here */ ],
    "Manchester City": [ /* Insert the 10 City Qs here */ ],
    "Liverpool": [ /* Insert the 10 Liverpool Qs here */ ],
    "Barcelona": [ /* Insert the 10 Barca Qs here */ ],

    // The 50 General Knowledge Questions (Top 5 Leagues & Europe)
    "General": [
        { q: "Which team won the 2015/16 Premier League?", options: ["Chelsea", "Leicester City", "Man City", "Spurs"], a: "Leicester City" },
        { q: "Who won the Golden Boot in the 2022 World Cup?", options: ["Messi", "Mbappé", "Giroud", "Neymar"], a: "Mbappé" },
        { q: "Which Italian team won 9 consecutive titles (2012-2020)?", options: ["Inter", "AC Milan", "Juventus", "Napoli"], a: "Juventus" },
        { q: "Who scored the winning goal for Germany in the 2014 World Cup Final?", options: ["Klose", "Müller", "Götze", "Özil"], a: "Götze" },
        { q: "Which coach has won the most Champions League titles?", options: ["Ferguson", "Guardiola", "Ancelotti", "Zidane"], a: "Ancelotti" },
        { q: "Which city hosted the 2023 UCL Final?", options: ["Paris", "Istanbul", "London", "Lisbon"], a: "Istanbul" },
        { q: "Who won the first-ever UEFA Conference League in 2022?", options: ["Feyenoord", "West Ham", "AS Roma", "Fiorentina"], a: "AS Roma" },
        { q: "Who is the all-time top scorer in Champions League history?", options: ["Messi", "Ronaldo", "Lewandowski", "Benzema"], a: "Ronaldo" },
        { q: "Which team won 3 consecutive Europa Leagues (2014-2016)?", options: ["Villarreal", "Sevilla", "Benfica", "Valencia"], a: "Sevilla" },
        { q: "Which nation won Euro 2024?", options: ["England", "France", "Spain", "Germany"], a: "Spain" },
        
        // --- Remaining 40 General Questions (Condensed for brevity) ---
        { q: "Who won the 2021 Ballon d'Or?", options: ["Lewandowski", "Messi", "Jorginho", "Benzema"], a: "Messi" },
        { q: "Which club does Xabi Alonso lead to an unbeaten Bundesliga in 2024?", options: ["Bayern", "Dortmund", "Leipzig", "Bayer Leverkusen"], a: "Bayer Leverkusen" },
        { q: "Which stadium is known as the 'Home of Football'?", options: ["Camp Nou", "Old Trafford", "Wembley", "Maracanã"], a: "Wembley" },
        { q: "Who was the most expensive player in 2017 (World Record)?", options: ["Mbappé", "Neymar", "Coutinho", "Dembele"], a: "Neymar" },
        { q: "Which French team won 7 titles in a row in the 2000s?", options: ["PSG", "Marseille", "Lyon", "Monaco"], a: "Lyon" },
        { q: "Who scored the fastest Premier League hat-trick?", options: ["Fowler", "Mané", "Aguero", "Son"], a: "Mané" },
        { q: "Which country hosted the 2018 World Cup?", options: ["Brazil", "Russia", "Qatar", "South Africa"], a: "Russia" },
        { q: "In 2019, which team lost the UCL final to Liverpool?", options: ["Ajax", "Barca", "Spurs", "Man City"], a: "Spurs" },
        { q: "Who won the 2020/21 Serie A, ending Juve's streak?", options: ["Napoli", "AC Milan", "Inter Milan", "Roma"], a: "Inter Milan" },
        { q: "Which player is nicknamed 'The Egyptian King'?", options: ["Elneny", "Salah", "Mido", "Mostafa"], a: "Salah" },
        { q: "Which club plays at the San Siro (sharing it)?", options: ["Lazio/Roma", "Inter/Milan", "Genoa/Sampdoria", "Juve/Torino"], a: "Inter/Milan" },
        { q: "Who won the 2022/23 treble?", options: ["Real Madrid", "Man City", "Bayern", "Liverpool"], a: "Man City" },
        { q: "Which player won the Euro 2024 Player of the Tournament?", options: ["Yamal", "Rodri", "Bellingham", "Olmo"], a: "Rodri" },
        { q: "Which team is nicknamed 'The Yellow Submarine'?", options: ["Dortmund", "Villarreal", "Cadiz", "Watford"], a: "Villarreal" },
        { q: "Who did Atletico Madrid beat in the 2018 Europa League final?", options: ["Marseille", "Arsenal", "Lyon", "Salzburg"], a: "Marseille" },
        { q: "Which manager is 'The Special One'?", options: ["Klopp", "Mourinho", "Pep", "Conte"], a: "Mourinho" },
        { q: "Who won the 2014 Golden Ball (Best Player)?", options: ["James Rodriguez", "Messi", "Müller", "Neuer"], a: "Messi" },
        { q: "Which club did Erling Haaland play for before Man City?", options: ["Molde", "Salzburg", "Dortmund", "Leipzig"], a: "Dortmund" },
        { q: "How many UCL titles does Barcelona have?", options: ["3", "4", "5", "6"], a: "5" },
        { q: "Who scored the winning goal in the 2010 World Cup (Legacy)?", options: ["Villa", "Torres", "Iniesta", "Xavi"], a: "Iniesta" },
        { q: "Which club is known as 'The Old Lady'?", options: ["Lazio", "Juventus", "Porto", "Milan"], a: "Juventus" },
        { q: "Who won the 2023 Women's World Cup?", options: ["England", "USA", "Spain", "Australia"], a: "Spain" },
        { q: "Which English player moved to Real Madrid in 2023?", options: ["Kane", "Rice", "Bellingham", "Saka"], a: "Bellingham" },
        { q: "Which Portuguese club is famous for its youth academy (Ronaldo/Bruno)?", options: ["Porto", "Benfica", "Sporting CP", "Braga"], a: "Sporting CP" },
        { q: "Who won the 2024 Ballon d'Or?", options: ["Vinicius Jr", "Rodri", "Bellingham", "Haaland"], a: "Rodri" },
        { q: "Which league is known as 'La Liga'?", options: ["Italian", "French", "Spanish", "Portuguese"], a: "Spanish" },
        { q: "Who is 'El Pistolero'?", options: ["Aguero", "Suarez", "Cavani", "Forlan"], a: "Suarez" },
        { q: "Which team won the 2021/22 Europa League?", options: ["Frankfurt", "Rangers", "West Ham", "Leipzig"], a: "Frankfurt" },
        { q: "Who managed Real Madrid to the 2024 UCL title?", options: ["Zidane", "Ancelotti", "Raul", "Alonso"], a: "Ancelotti" },
        { q: "Which city is PSG based in?", options: ["Marseille", "Lyon", "Paris", "Nice"], a: "Paris" },
        { q: "Who won the 2019 Copa America?", options: ["Argentina", "Brazil", "Chile", "Peru"], a: "Brazil" },
        { q: "Which stadium is the largest in Europe?", options: ["Wembley", "Camp Nou", "Bernabeu", "Signal Iduna"], a: "Camp Nou" },
        { q: "Who is the current manager of the German National team (2025/26)?", options: ["Klopp", "Nagelsmann", "Flick", "Tuchel"], a: "Nagelsmann" },
        { q: "Which club did Harry Kane join in 2023?", options: ["Man City", "Real Madrid", "Bayern Munich", "PSG"], a: "Bayern Munich" },
        { q: "Who won the 2016 Euros?", options: ["France", "Portugal", "Germany", "Wales"], a: "Portugal" },
        { q: "Which player has the most Premier League assists ever?", options: ["Fabregas", "Rooney", "Giggs", "De Bruyne"], a: "Giggs" },
        { q: "Which team won the 2023/24 FA Cup?", options: ["Man City", "Man United", "Liverpool", "Chelsea"], a: "Man United" },
        { q: "Who is the captain of the French National team (2026)?", options: ["Griezmann", "Mbappé", "Saliba", "Maignan"], a: "Mbappé" },
        { q: "Which club did Zlatan Ibrahimovic retire at?", options: ["PSG", "Man Utd", "AC Milan", "LA Galaxy"], a: "AC Milan" },
        { q: "Which team plays at the 'Yellow Wall' stadium?", options: ["Bayern", "Dortmund", "Villarreal", "Arsenal"], a: "Dortmund" }
    ]
};
